### PR TITLE
Fix TS 4.9 compatibility

### PR DESCRIPTION
**Pull request by SRChiP**
Why:

The litegraph library fails to compile with typescript4.9+ in Angular 16. This is because TS isn't aware that we extended a bult-in  DOM object prototype

This change addresses the need by:

* Remove extending the Math & CanvasRenderingContext2D classes. It was messing up the typescript 4.9+
* Use utility classes instead of that extended functionality
* Add some type corrections in litegraph.d.ts
* Fix a couple of build issues

Optional details:

The error we get is 
```
Error: node_modules/typescript/lib/lib.dom.d.ts:3654:11 - error TS2430: Interface 'CanvasRenderingContext2D' incorrectly extends interface 'CanvasPath'.
  Types of property 'roundRect' are incompatible.
    Type '(x: number, y: number, width: number, height: number, radius: number, radiusLow: number) => void' is not assignable to type '(x: number, y: number, w: number, h: number, radii?: number | DOMPointInit | (number | DOMPointInit)[] | undefined) => void'.

3654 interface CanvasRenderingContext2D extends CanvasCompositing, CanvasDrawImage, CanvasDrawPath, CanvasFillStrokeStyles, CanvasFilters, CanvasImageData, CanvasImageSmoothing, CanvasPath, CanvasPathDrawingStyles, CanvasRect, CanvasShadowStyles, CanvasState, CanvasText, CanvasTextDrawingStyles, CanvasTransform, CanvasUserInterface {
     
```

### CODE REVIEW

**Comment by SRChiP** [comment]
I've added all the changed files/docs. Let me know if we don't need to commit those
